BurningSns/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from . import views

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'BurningSns.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$|^index&', views.index_view, name="index"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('accounts.urls', namespace="account")),
    url(r'^home/', include('website.urls', namespace='home')),
)

accounts/urls.py
'''
Created on 2013年12月12日

@author: july
'''
from django.conf.urls import patterns, url

from accounts import views

urlpatterns = patterns('',
    url(r'^logout$', views.logout_view, name = "logout"),
    url(r'^login$|^$', views.login_view, name = "login"),
    url(r'^register$', views.register_view, name = "register"),
    url(r'^twoacf$', views.tw_oauth_confirm, name = "tw_oauth_confirm"),
    url(r'^twoarq$', views.tw_oauth_request, name = "tw_oauth_request"),
    url(r'^sw_oauth_confirm$', views.sw_oauth_confirm, name = "sw_oauth_confirm"),
    url(r'^sw_oauth_request$', views.sw_oauth_request, name = "sw_oauth_request"),
    url(r'^oauthmanage$',views.oauth_manage_view, name = 'oauth_manage'),
    url(r'^destroy_oauth/(?P<site>\w+)}',views.destroy_oauth,name= 'destroy_oauth')
)

website/urls.py
from django.conf.urls import patterns, url

from website import views

urlpatterns = patterns('',
   url(r'^$|^content$', views.content_view, name = "content"),
   url(r'^$|^statuses', views.statuses_view, name = "statuses"),
)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}微辣 BURNING - PYTHON{% endblock %}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    {% block head %}{% endblock %}
    <style>
        body{
            display: block;
            padding:0;
            margin:0;
            background-position: center 0;
            background-repeat: no-repeat;
            background-image: url("{% static "website/images/body_bg.png" %}");
            background-color: #BEE1F5;
        }
        .head{
            width:100%;
            height:40px;
            background-color: purple;
            box-shadow: 0 5px 3px gray;
        }
        .body{
            width:960px;
            height:auto;
            min-height: 400px;
            margin:25px auto;
            background: white;
        }
        .side-left{
            width:150px;
            background: #EFEFEF;
            float:left;
            min-height: 400px;
        }
        .content{
            width:600px;
            background: white;
            float:left;
            box-shadow: #d9d9d9 -2px 0 2px;
            min-height: 400px;
        }
        .side-right{
            width:208px;
            background: white;
            float:right;
            border-left: solid 2px #D9D9D9;
            min-height: 400px;
        }
    </style>
</head>
<body>
<div class="head">

</div>
<div class="body">
    <div class="side-left">
        {% block side_left %}
            左边栏
        {% endblock %}
    </div>
    <div class="content">
        {% block content %}

        {% endblock %}
    </div>
    <div class="side-right">
        {% block side_right %}
            右边栏
        {% endblock %}
    </div>
</div>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
<div>
    {% if user %}
        <p>hello,{{ user.username }}!</p>
        <a href="{% url 'account:logout' %}">退出</a>
        <a href="{% url 'account:oauth_manage' %}">管理我的社交网络账号</a>
    {% else %}
        <a href= {% url 'account:login' %}>登录</a>
        <a href= {% url 'account:register' %}>注册</a>
        <a href= {% url 'account:tw_oauth_request' %}>使用腾讯微博登陆</a>
    {% endif %}
    <a href="/admin">管理</a>
</div>
{% endblock %}